from voice.agents.registry import FEMALE_VOICES

GENDER_TOKENS = {
    ("ur-PK", "female"): {
        "name": "Zara",
        "gender_desc": "You are female (Zara).",
        "gender_form": "feminine",
        "kar_rahi_hoon": "kar rahi hoon",
        "laga_rahi_hoon": "laga rahi hoon",
        "sakti_hoon": "sakti hoon",
        "chahti_hoon": "chahti hoon",
        "sakti": "sakti",
        "chahti": "chahti",
        "wali_hoon": "wali hoon",
        "filler_menu": "Ek minute, main menu check kar rahi hoon.",
        "filler_order": "Ek minute, main aap ka order laga rahi hoon.",
        "order_kya": "Aap kya order karna chahain gay?",
        "confirm_opener": "To main confirm karna chahti hoon",
        "drink_ask": "Aap ke saath kaunsa drink lena chahain gay?",
        "order_success_delivery": "Aap ka order kamyabi se lag gaya! 30 se 45 minutes mein pohanch jaye ga!",
        "order_success_pickup": "Aap ka order kamyabi se lag gaya! Aap BlenSpark Cafe se pick kar sakte hain!",
        "order_fail": "Sorry, system mein issue aa gaya hai. Please thori der baad try karein.",
        "closing_line": "Humain choose karne ka shukriya! Allah Hafiz!",
        "system_error": "Maafi chahti hoon, system mein abhi masla hai. Thori der baad call karein.",
        "mandatory_wait": "Please wait, main aap ka order system mein enter kar rahi hoon.",
    },
    ("ur-PK", "male"): {
        "name": "Ali",
        "gender_desc": "You are male (Ali).",
        "gender_form": "masculine",
        "kar_rahi_hoon": "kar raha hoon",
        "laga_rahi_hoon": "laga raha hoon",
        "sakti_hoon": "sakta hoon",
        "chahti_hoon": "chahta hoon",
        "sakti": "sakta",
        "chahti": "chahta",
        "wali_hoon": "wala hoon",
        "filler_menu": "Ek minute, main menu check kar raha hoon.",
        "filler_order": "Ek minute, main aap ka order laga raha hoon.",
        "order_kya": "Aap kya order karna chahain gay?",
        "confirm_opener": "To main confirm karna chahta hoon",
        "drink_ask": "Aap ke saath kaunsa drink lena chahain gay?",
        "order_success_delivery": "Aap ka order kamyabi se lag gaya! 30 se 45 minutes mein pohanch jaye ga!",
        "order_success_pickup": "Aap ka order kamyabi se lag gaya! Aap BlenSpark Cafe se pick kar sakte hain!",
        "order_fail": "Sorry, system mein issue aa gaya hai. Please thori der baad try karein.",
        "closing_line": "Humain choose karne ka shukriya! Allah Hafiz!",
        "system_error": "Maafi chahta hoon, system mein abhi masla hai. Thori der baad call karein.",
        "mandatory_wait": "Please wait, main aap ka order system mein enter kar raha hoon.",
    },
    ("en-US", "female"): {
        "name": "Zara",
        "gender_desc": "You are female (Zara).",
        "gender_form": "feminine",
        "filler_menu": "One moment, let me check the menu.",
        "filler_order": "One moment, I'm placing your order now.",
        "confirm_opener": "Let me confirm your order",
        "drink_ask": "Which drink would you like with your burger?",
        "item_unavailable": "Sorry, that item isn't on our menu. Is there something else I can help you with?",
        "order_success_delivery": "Your order has been placed successfully! It will arrive in 30 to 45 minutes.",
        "order_success_pickup": "Your order has been placed! You can pick it up from BlenSpark Cafe.",
        "order_fail": "Sorry, there was a system issue. Please try again in a few minutes.",
        "closing_line": "Thank you for choosing us! Have a great day. Goodbye!",
        "system_error": "I'm sorry, there seems to be a system issue right now. Please call back shortly.",
    },
    ("en-US", "male"): {
        "name": "Ali",
        "gender_desc": "You are male (Ali).",
        "gender_form": "masculine",
        "filler_menu": "One moment, let me check the menu.",
        "filler_order": "One moment, I'm placing your order now.",
        "confirm_opener": "Let me confirm your order",
        "drink_ask": "Which drink would you like with your burger?",
        "item_unavailable": "Sorry, that item isn't on our menu. Is there something else I can get for you?",
        "order_success_delivery": "Your order has been placed successfully! It will arrive in 30 to 45 minutes.",
        "order_success_pickup": "Your order has been placed! You can pick it up from BlenSpark Cafe.",
        "order_fail": "Sorry, there was a system issue. Please try again in a few minutes.",
        "closing_line": "Thank you for choosing us! Have a great day. Goodbye!",
        "system_error": "I'm sorry, there seems to be a system issue right now. Please call back shortly.",
    },
}
