# Generated by Django 5.2.11 on 2026-04-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0005_geminisessioncost_input_text_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminisessioncost',
            name='cost_calculation_method',
            field=models.CharField(choices=[('modality', 'Precise modality breakdown'), ('blended_fallback', 'Blended fallback rates')], default='modality', help_text='Which calculation method was used: modality (precise) or blended_fallback (when modality details missing)', max_length=50),
        ),
    ]
