from voice.agents.registry import FEMALE_VOICES

DAY_NAMES = {0: "Monday", 1: "Tuesday", 2: "Wednesday", 3: "Thursday", 4: "Friday", 5: "Saturday", 6: "Sunday"}

GENDER_TOKENS = {
    ("ur-PK", "female"): {
        "name": "Sara",
        "gender_desc": "You are female (Sara).",
        "gender_form": "feminine",
        "rahi_hoon": "rahi hoon",
        "kar_rahi_hoon": "kar rahi hoon",
        "karti_hoon": "karti hoon",
        "sakti_hoon": "sakti hoon",
        "chahti_hoon": "chahti hoon",
        "karti": "karti",
        "sakti": "sakti",
        "chahti": "chahti",
        "filler_schedule": "Ek minute, main schedule check kar rahi hoon.",
        "filler_slots": "Ek minute, main available slots check kar rahi hoon.",
        "filler_book": "Ek minute, main aap ki appointment book kar rahi hoon.",
        "confirm_line": "To main confirm karna chahti hoon",
        "slot_conflict": "Sorry, yeh slot pehle se book hai. Ek minute, main doosray slots check kar rahi hoon.",
        "no_slots_line": "Afsos, is din tamam slots bhar gayi hain. Kya main agla open day check karoon?",
        "closing_line": "Humain call karne ka shukriya! Allah Hafiz!",
    },
    ("ur-PK", "male"): {
        "name": "Ali",
        "gender_desc": "You are male (Ali).",
        "gender_form": "masculine",
        "rahi_hoon": "raha hoon",
        "kar_rahi_hoon": "kar raha hoon",
        "karti_hoon": "karta hoon",
        "sakti_hoon": "sakta hoon",
        "chahti_hoon": "chahta hoon",
        "karti": "karta",
        "sakti": "sakta",
        "chahti": "chahta",
        "filler_schedule": "Ek minute, main schedule check kar raha hoon.",
        "filler_slots": "Ek minute, main available slots check kar raha hoon.",
        "filler_book": "Ek minute, main aap ki appointment book kar raha hoon.",
        "confirm_line": "To main confirm karna chahta hoon",
        "slot_conflict": "Sorry, yeh slot pehle se book hai. Ek minute, main doosray slots check kar raha hoon.",
        "no_slots_line": "Afsos, is din tamam slots bhar gaye hain. Kya main agla open day check karoon?",
        "closing_line": "Humain call karne ka shukriya! Allah Hafiz!",
    },
    ("en-US", "female"): {
        "name": "Sarah",
        "gender_desc": "You are female (Sarah).",
        "gender_form": "feminine",
        "filler_schedule": "One moment, let me check the schedule.",
        "filler_slots": "One moment, let me check available slots for that day.",
        "filler_book": "One moment, I'm booking your appointment now.",
        "confirm_opener": "Let me confirm everything before I book",
        "slot_conflict": "Sorry, that slot was just taken. Let me check other available times for you.",
        "no_slots_line": "I'm sorry, all slots for that day are fully booked. Shall I check the next available day?",
        "closing_line": "Thank you for calling! Have a great day. Goodbye!",
        "booking_success": "I've successfully booked your appointment",
        "checking_next": "Let me check the next available day for you.",
        "unsure_suggest": "May I suggest tomorrow or the next open day?",
    },
    ("en-US", "male"): {
        "name": "Alex",
        "gender_desc": "You are male (Alex).",
        "gender_form": "masculine",
        "filler_schedule": "One moment, let me check the schedule.",
        "filler_slots": "One moment, let me check available slots for that day.",
        "filler_book": "One moment, I'm booking your appointment now.",
        "confirm_opener": "Let me confirm everything before I book",
        "slot_conflict": "Sorry, that slot was just taken. Let me check other available times for you.",
        "no_slots_line": "I'm sorry, all slots for that day are fully booked. Shall I check the next available day?",
        "closing_line": "Thank you for calling! Have a great day. Goodbye!",
        "booking_success": "I've successfully booked your appointment",
        "checking_next": "Let me check the next available day for you.",
        "unsure_suggest": "May I suggest tomorrow or the next open day?",
    },
}
